from django.core.management.base import BaseCommand, CommandError
from calc.models import Concrete, Use


class Command(BaseCommand):
    def handle(self, *args, **options):
        c1 = Concrete.objects.get(id=1)
        c2 = Concrete.objects.get(id=2)
        c3 = Concrete.objects.get(id=3)
        c4 = Concrete.objects.get(id=4)
        c5 = Concrete.objects.get(id=5)
        c6 = Concrete.objects.get(id=6)
        c7 = Concrete.objects.get(id=7)
        c8 = Concrete.objects.get(id=8)
        c9 = Concrete.objects.get(id=9)
        c10 = Concrete.objects.get(id=10)

        u1 = Use.objects.get(id=1)
        u2 = Use.objects.get(id=2)
        u3 = Use.objects.get(id=3)
        u4 = Use.objects.get(id=4)
        u5 = Use.objects.get(id=5)
        u6 = Use.objects.get(id=6)
        u7 = Use.objects.get(id=7)
        u8 = Use.objects.get(id=8)

        # Conrete - related_name (w Use do Concrete)
        c1.uses.add(u3)
        c1.uses.add(u7)
        c1.uses.add(u8)

        # Use - conc (w Use do Concrete)
        u1.conc.add(c2)
        u1.conc.add(c3)
        u1.conc.add(c4)
        u2.conc.add(c3)
        u2.conc.add(c4)
        u2.conc.add(c5)
        u3.conc.add(c1)
        u3.conc.add(c2)
        u4.conc.add(c3)
        u4.conc.add(c4)
        u4.conc.add(c5)
        u4.conc.add(c6)
        u5.conc.add(c3)
        u5.conc.add(c4)
        u5.conc.add(c5)
        u5.conc.add(c6)
        u6.conc.add(c3)
        u6.conc.add(c4)
        u6.conc.add(c5)
        u6.conc.add(c6)
        u7.conc.add(c1)
        u7.conc.add(c2)
        u7.conc.add(c3)
        u7.conc.add(c4)
        u7.conc.add(c5)
        u8.conc.add(c1)
        u8.conc.add(c2)
        u8.conc.add(c3)
        u8.conc.add(c4)
        u8.conc.add(c5)
        u8.conc.add(c6)
        u8.conc.add(c7)
        u8.conc.add(c8)
        u8.conc.add(c9)
        u8.conc.add(c10)
